version: '3.8'

services:
  db:
    container_name: db
    image: postgres:latest
    ports:
      - "6432:5432"
    environment:
      - POSTGRES_PASSWORD=12345
      - POSTGRES_DB=scrapper_db
      - POSTGRES_USER=aigunov
    networks:
      - backend

  liquibase:
    container_name: liquibase
    image: liquibase/liquibase:4.29
    depends_on:
      - db
    command:
      - --changeLogFile=db.changelog-master.xml
      - --url=jdbc:postgresql://db:5432/scrapper_db
      - --username=aigunov
      - --password=12345
      - update
    volumes:
      - ./migrations:/migrations
    working_dir: /migrations
    networks:
      - backend

  zookeeper:
    container_name: zookeeper
    image: confluentinc/cp-zookeeper:7.5.0
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - backend

  kafka:
    container_name: kafka
    image: confluentinc/cp-kafka:7.5.0
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,PLAINTEXT_INTERNAL://0.0.0.0:29092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092,PLAINTEXT_INTERNAL://kafka:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT_INTERNAL
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      - backend


  redis:
    container_name: redis
    image: redis:latest
    ports:
      - "6379:6379"
    command: [ "redis-server", "--requirepass", "12345", "--user", "aigunov", "on", ">12345", "~*", "+@all" ]
    networks:
      - backend


networks:
  backend:
