version: '3.8'

services:
  db:
    container_name: db
    image: postgres:latest
    ports:
      - "6432:5432"
    environment:
      - POSTGRES_PASSWORD=12345
      - POSTGRES_DB=scrapper_db
      - POSTGRES_USER=aigunov
    networks:
      - backend

  liquibase:
    container_name: liquibase
    image: liquibase/liquibase:4.29
    depends_on:
      - db
    command:
      - --changeLogFile=db.changelog-master.xml
      - --url=jdbc:postgresql://postgresql:5432/${POSTGRES_DB}
      - --username=aigunov
      - --password=12345
      - update
    volumes:
      - ./migrations:/migrations
    networks:
      - backend

networks:
  backend:
