version: '3.8'

services:
  postgresql:
    container_name: postgresql
    image: postgres:latest
    ports:
      - "6432:5432"
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
    networks:
      - backend

  liquibase:
    container_name: liquibase
    image: liquibase/liquibase:4.29
    depends_on:
      - postgresql
    command:
      - --changeLogFile=db.changelog-master.xml
      - --url=jdbc:postgresql://postgresql:5432/${POSTGRES_DB}
      - --username=${POSTGRES_USER}
      - --password=${POSTGRES_PASSWORD}
      - update
    volumes:
      - ./migrations:/migrations
    networks:
      - backend

networks:
  backend:
