app:
  github:
    token: ${GITHUB_TOKEN}
    url: https://api.github.com/repos

  stackoverflow:
    url: https://api.stackexchange.com/2.3/questions
    key: ${SO_TOKEN_KEY}
    access-token: ${SO_ACCESS_TOKEN}
  db:
    access-type: sql

  message:
    transport: kafka
    kafka:
      topic:
        notification: notification-topic
        digest: digest-topic
        dead-letter: notification-dead-letter-topic

  bot:
    url: http://localhost:8080
  scrapper:
    threads-count: ${THREADS_COUNT}
    scheduled-time: ${SCHEDULED_TIME}
    page-size: ${PAGE_SIZE}
  digest:
    scheduler-time: ${REDIS_SCHEDULED_TIME:60000}
    threads-count: ${REDIS_THREADS_COUNT:4}


spring:
  application:
    name: Scrapper
  datasource:
    url: jdbc:postgresql://localhost:6432/scrapper_db
    username: aigunov
    password: 12345
  liquibase:
    enabled: false
    change-log: classpath:migrations/db.changelog-master.xml
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
  kafka:
    bootstrap-servers: localhost:9092
  data:
    redis:
      username: ${REDIS_USERNAME}
      password: ${REDIS_PASSWORD}
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}

server:
  port: 8081

rate-limiting:
  capacity: 100
  duration: 1m

springdoc:
  swagger-ui:
    enabled: true
    path: /swagger-ui


resilience4j:
  circuitbreaker:
    instances:
      gitHubClient:
        registerHealthIndicator: true
        slidingWindowType: COUNT_BASED
        slidingWindowSize: 1
        minimumNumberOfCalls: 1
        failureRateThreshold: 100
        permittedNumberOfCallsInHalfOpenState: 1
        waitDurationInOpenState: 1s

      stackOverflowClient:
        registerHealthIndicator: true
        slidingWindowType: COUNT_BASED
        slidingWindowSize: 1
        minimumNumberOfCalls: 1
        failureRateThreshold: 100
        permittedNumberOfCallsInHalfOpenState: 1
        waitDurationInOpenState: 1s

client:
  resilience:
    github-client:
      timeout: 10s
      max-attempts: 3
      wait-duration: 21s
      retry-statuses:
        - 502
        - 503
        - 504
      rate-limit-for-period: 20
      rate-limit-refresh-period: 10s

    stackoverflow-client:
      timeout: 10s
      max-attempts: 3
      wait-duration: 2s
      retry-statuses:
        - 502
        - 503
        - 504
      rate-limit-for-period: 20
      rate-limit-refresh-period: 10s


    bot-client:
      timeout: 2s
      max-attempts: 3
      wait-duration: 1s
      retry-statuses:
        - 502
        - 503
        - 504
        - 500
        - 429
      rate-limit-for-period: 20
      rate-limit-refresh-period: 10s

logging:
  level:
    org.springframework.web.client: DEBUG
    com.github.tomakehurst.wiremock: DEBUG
    wiremock.org.eclipse.jetty: DEBUG
    wiremock.org.eclipse.jetty.server: DEBUG
    wiremock.org.eclipse.jetty.util: DEBUG
    com.github.tomakehurst.wiremock.common.Slf4jNotifier: DEBUG
