app:
  github:
    token: ${GITHUB_TOKEN}
    url: https://api.github.com/repos

  stackoverflow:
    url: https://api.stackexchange.com/2.3/questions
    key: ${SO_TOKEN_KEY}
    access-token: ${SO_ACCESS_TOKEN}
  db:
    access-type: sql

  message:
    transport: kafka
    kafka:
      topic:
        notification: notification-topic
        digest: digest-topic
        dead-letter: notification-dead-letter-topic

  bot:
    url: http://localhost:8080
  scrapper:
    threads-count: ${THREADS_COUNT}
    scheduled-time: ${SCHEDULED_TIME}
    page-size: ${PAGE_SIZE}
  digest:
    scheduler-time: 60000
    threads-count: 4


spring:
  application:
    name: Scrapper
  datasource:
    url: jdbc:postgresql://localhost:6432/scrapper_db
    username: aigunov
    password: 12345
  liquibase:
    enabled: false
    change-log: classpath:migrations/db.changelog-master.xml
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
  kafka:
    bootstrap-servers: localhost:9092
  data:
    redis:
      username: aigunov
      password: 12345
      host: localhost
      port: 6379

server:
  port: 8081

springdoc:
  swagger-ui:
    enabled: true
    path: /swagger-ui


