app:
  telegram-token: ${TELEGRAM_TOKEN} # env variable

  message:
    transport: ${MESSAGE_TRANSPORT}
    kafka:
      topic:
        notification: notification-topic
        dead-letter: notifaction-dead-letter-topic


spring:
  application:
    name: Bot
  liquibase:
    enabled: false
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
  kafka:
    bootstrap-servers: kafka:9093
  data:
    redis:
      username: aigunov
      password: 12345
      host: localhost
      port: 6379

server:
  port: 8080

springdoc:
  swagger-ui:
    enabled: true
    path: /swagger-ui


scrapper:
  api:
    url: http://localhost:8081
