app:
  telegram-token: ${TELEGRAM_TOKEN} # env variable

  message:
    transport: kafka
    kafka:
      topic:
        notification: notification-topic
        digest: digest-topic
        dead-letter: notification-dead-letter-topic


spring:
  application:
    name: Bot
  liquibase:
    enabled: false
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
  data:
    redis:
      username: aigunov
      password: 12345
      host: localhost
      port: 6379

server:
  port: 8080

springdoc:
  swagger-ui:
    enabled: true
    path: /swagger-ui


scrapper:
  api:
    url: http://localhost:8081
